import { Link, useNavigate } from 'react-router-dom';
import { useEffect } from 'react';
import { ArrowLeft, TrendingUp, BarChart3, Activity, Target, Eye, BookOpen } from 'lucide-react';

export default function TechnicalAnalysisBasics() {
  const navigate = useNavigate();

  useEffect(() => {
    const isAuthenticated = localStorage.getItem('isAuthenticated') === 'true';
    if (!isAuthenticated) {
      navigate('/login', { state: { from: '/technical-analysis/basics' } });
    }
  }, [navigate]);

  const topics = [
    { id: 'what-is-ta', title: 'What is Technical Analysis?', icon: BookOpen },
    { id: 'core-philosophy', title: 'Core Philosophy', icon: Target },
    { id: 'price-volume-time', title: 'Price, Volume & Time', icon: Activity },
    { id: 'chart-types', title: 'Types of Charts', icon: BarChart3 },
    { id: 'dow-theory', title: 'Dow Theory Basics', icon: TrendingUp },
    { id: 'ta-vs-fa', title: 'Technical vs Fundamental', icon: Eye }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-800 pt-24 pb-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
        {/* Header */}
        <Link to="/technical-analysis" className="inline-flex items-center text-blue-600 hover:text-blue-700 mb-6 sm:mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4 sm:w-5 sm:h-5 mr-2" />
          Back to Technical Analysis
        </Link>

        <div className="mb-8 sm:mb-12">
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-white mb-4 sm:mb-6">
            Basics of Technical Analysis
          </h1>
          <p className="text-base sm:text-lg text-slate-300 max-w-3xl">
            Technical analysis is the study of historical price movements to forecast future price direction. Unlike fundamental analysis which studies company financials, technical analysis focuses purely on price action, volume, and market psychology.
          </p>
        </div>

        {/* Quick Navigation */}
        <div className="bg-white rounded-xl shadow-lg p-4 sm:p-6 md:p-8 mb-8 sm:mb-12">
          <h2 className="text-xl sm:text-2xl font-bold text-slate-900 mb-4 sm:mb-6">Quick Navigation</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 sm:gap-4">
            {topics.map((topic) => {
              const Icon = topic.icon;
              return (
                <a
                  key={topic.id}
                  href={`#${topic.id}`}
                  className="flex items-center p-3 sm:p-4 bg-gradient-to-r from-blue-50 to-cyan-50 rounded-lg hover:from-blue-100 hover:to-cyan-100 transition-all group"
                >
                  <Icon className="w-5 h-5 sm:w-6 sm:h-6 text-blue-600 mr-3 group-hover:scale-110 transition-transform" />
                  <span className="text-sm sm:text-base font-medium text-slate-800">{topic.title}</span>
                </a>
              );
            })}
          </div>
        </div>

        {/* Content Sections */}
        <div className="space-y-8 sm:space-y-12">

          {/* 1. What is Technical Analysis */}
          <div id="what-is-ta" className="bg-white rounded-xl shadow-lg p-4 sm:p-6 md:p-8">
            <div className="border-l-4 border-blue-500 pl-4 sm:pl-6">
              <h2 className="text-2xl sm:text-3xl font-bold text-white mb-4 sm:mb-6">1. What is Technical Analysis?</h2>
              <div className="space-y-6">
                <p className="text-sm sm:text-base text-slate-700 leading-relaxed">
                  Technical analysis is a method of evaluating securities by analyzing statistics generated by market activity, such as past prices and volume. Technical analysts don't attempt to measure a security's intrinsic value; instead, they use charts and other tools to identify patterns that can suggest future activity.
                </p>
                
                <div className="bg-blue-50 rounded-lg p-4 sm:p-5 border-2 border-blue-200">
                  <p className="text-xs sm:text-sm text-slate-700">
                    <strong>Simple Definition:</strong> Technical analysis is the study of price charts to predict where prices will go next. It assumes that all known information is already reflected in the price, and that price patterns repeat themselves over time due to consistent human psychology.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* 2. Core Philosophy */}
          <div id="core-philosophy" className="bg-white rounded-xl shadow-lg p-4 sm:p-6 md:p-8">
            <div className="border-l-4 border-cyan-500 pl-4 sm:pl-6">
              <h2 className="text-2xl sm:text-3xl font-bold text-slate-800 mb-4 sm:mb-6">2. Core Philosophy of Technical Analysis</h2>
              
              <div className="mb-6">
                <h3 className="text-lg sm:text-xl font-semibold text-cyan-700 mb-3">Three Fundamental Assumptions</h3>
              </div>
                <h3 className="text-lg sm:text-xl font-semibold text-cyan-700 mb-3">Three Fundamental Assumptions</h3>
                <p className="text-sm sm:text-base text-slate-700 mb-4">
                  Technical analysis is based on three fundamental assumptions that form the bedrock of all chart-based trading strategies. Understanding these principles is crucial before diving into patterns and indicators.
                </p>
                <div className="space-y-4 sm:space-y-6">
                  <div className="bg-cyan-50 rounded-lg p-4 sm:p-5 border-l-4 border-cyan-400">
                    <div className="flex items-start gap-3">
                      <span className="text-2xl sm:text-3xl">💡</span>
                      <div>
                        <strong className="text-base sm:text-lg text-slate-900">1. Market Discounts Everything</strong>
                        <p className="text-xs sm:text-sm text-slate-700 mt-2 mb-3">All information—fundamental data, political events, natural disasters, psychological sentiment—is already reflected in the current price. Therefore, studying price movements alone is sufficient to make trading decisions.</p>
                        <div className="bg-blue-50 rounded p-3 text-xs sm:text-sm text-slate-600">
                          <strong>Example:</strong> If a company announces great earnings but the stock price drops, it means the market expected even better results. The price already "knew" this before you did.
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="bg-green-50 rounded-lg p-4 sm:p-5 border-l-4 border-green-400">
                    <div className="flex items-start gap-3">
                      <span className="text-2xl sm:text-3xl">📈</span>
                      <div>
                        <strong className="text-base sm:text-lg text-slate-900">2. Price Moves in Trends</strong>
                        <p className="text-xs sm:text-sm text-slate-700 mt-2 mb-3">Once a trend is established (up, down, or sideways), it tends to continue rather than reverse. This persistence is due to momentum—mass psychology doesn't change instantly. Newton's first law applies: objects in motion tend to stay in motion.</p>
                        <div className="bg-green-50 rounded p-3 text-xs sm:text-sm text-slate-600">
                          <strong>Trading Implication:</strong> "The trend is your friend." Fighting established trends leads to losses. Trend-following strategies work because of this principle.
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="bg-purple-50 rounded-lg p-4 sm:p-5 border-l-4 border-purple-400">
                    <div className="flex items-start gap-3">
                      <span className="text-2xl sm:text-3xl">🔁</span>
                      <div>
                        <strong className="text-base sm:text-lg text-slate-900">3. History Repeats Itself</strong>
                        <p className="text-xs sm:text-sm text-slate-700 mt-2 mb-3">Market psychology is predictable because human emotions—fear, greed, hope, panic—are consistent over time. Similar chart patterns that worked 50 years ago still work today because human nature hasn't changed.</p>
                        <div className="bg-purple-50 rounded p-3 text-xs sm:text-sm text-slate-600">
                          <strong>Historical Evidence:</strong> Charles Dow developed these principles in the 1890s. 130+ years later, the same patterns (head & shoulders, double tops, triangles) continue to predict price moves with remarkable accuracy.
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div className="bg-cyan-50 border-l-4 border-cyan-400 p-4 sm:p-6 rounded mt-6">
                <h4 className="font-semibold text-slate-900 mb-2 text-sm sm:text-base">🎯 Why This Matters</h4>
                <p className="text-xs sm:text-sm text-slate-700">
                  These three principles justify why looking at charts can predict future prices. If price didn't discount everything, you'd need insider info. If trends didn't exist, every move would be random. If history didn't repeat, patterns would be useless.
                </p>
              </div>
            </div>
          </div>

          {/* 3. Technical vs Fundamental Analysis */}
          <div id="ta-vs-fa" className="bg-white rounded-xl shadow-lg p-4 sm:p-6 md:p-8">
            <div className="border-l-4 border-purple-500 pl-4 sm:pl-6">
              <h2 className="text-2xl sm:text-3xl font-bold text-slate-800 mb-4 sm:mb-6">3. Technical vs Fundamental Analysis</h2>
              
              <div className="mb-6">
                <h3 className="text-lg sm:text-xl font-semibold text-purple-700 mb-3">Comparing Two Approaches</h3>
                <div className="grid sm:grid-cols-2 gap-4 sm:gap-6">
                  <div className="bg-purple-50 rounded-lg p-4 sm:p-5 border-2 border-purple-200">
                    <h4 className="font-semibold text-purple-900 mb-3 text-sm sm:text-base">📊 Technical Analysis</h4>
                    <ul className="space-y-2 text-xs sm:text-sm text-slate-700">
                      <li>• Studies price charts and patterns</li>
                      <li>• Focuses on market psychology</li>
                      <li>• Short to medium-term trading</li>
                      <li>• Uses indicators and oscillators</li>
                      <li>• Works across all timeframes</li>
                      <li>• Answers: <strong>When to buy/sell?</strong></li>
                    </ul>
                  </div>
                <div className="bg-white rounded-lg p-4">
                  <h4 className="font-semibold text-green-700 mb-3">Fundamental Analysis</h4>
                  <ul className="space-y-2 text-sm text-slate-600">
                    <li>• Studies company financials</li>
                    <li>• Focuses on intrinsic value</li>
                    <li>• Long-term investing</li>
                    <li>• Uses financial ratios</li>
                    <li>• Company-specific analysis</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Price, Volume & Time */}
        <div className="bg-white rounded-2xl p-8 shadow-lg mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-6">The Three Pillars: Price, Volume & Time</h2>
          <div className="space-y-6">
            <p className="text-lg text-slate-700">
              Technical analysis revolves around three critical components that form the foundation of market analysis:
            </p>

            <div className="space-y-6">
              <div className="border-l-4 border-blue-500 pl-6 py-2">
                <h3 className="text-xl font-semibold text-slate-900 mb-3">1. Price</h3>
                <p className="text-slate-700 mb-3">
                  Price is the most important element. It reflects the current consensus between buyers and sellers. Every price level represents the point where supply equals demand at that moment.
                </p>
                <div className="bg-slate-50 rounded-lg p-4">
                  <p className="text-sm text-slate-600 mb-2"><strong>Key Concepts:</strong></p>
                  <ul className="space-y-1 text-sm text-slate-600 ml-4">
                    <li>• <strong>Open:</strong> First traded price in a period</li>
                    <li>• <strong>High:</strong> Highest price reached in a period</li>
                    <li>• <strong>Low:</strong> Lowest price reached in a period</li>
                    <li>• <strong>Close:</strong> Final traded price in a period</li>
                  </ul>
                  <p className="text-sm text-slate-600 mt-3">
                    The relationship between Open, High, Low, Close (OHLC) tells us about market sentiment and strength.
                  </p>
                </div>
              </div>

              <div className="border-l-4 border-green-500 pl-6 py-2">
                <h3 className="text-xl font-semibold text-slate-900 mb-3">2. Volume</h3>
                <p className="text-slate-700 mb-3">
                  Volume represents the total number of shares or contracts traded during a specific period. It confirms the strength of a price move. High volume indicates strong conviction; low volume suggests weak participation.
                </p>
                <div className="bg-slate-50 rounded-lg p-4">
                  <p className="text-sm text-slate-600 mb-2"><strong>Volume Principles:</strong></p>
                  <ul className="space-y-2 text-sm text-slate-600 ml-4">
                    <li>• <strong>Price up + Volume up:</strong> Strong bullish signal (buyers in control)</li>
                    <li>• <strong>Price down + Volume up:</strong> Strong bearish signal (sellers in control)</li>
                    <li>• <strong>Price up + Volume down:</strong> Weak rally (possible reversal)</li>
                    <li>• <strong>Price down + Volume down:</strong> Weak decline (selling pressure exhausted)</li>
                  </ul>
                </div>
              </div>

              <div className="border-l-4 border-purple-500 pl-6 py-2">
                <h3 className="text-xl font-semibold text-slate-900 mb-3">3. Time</h3>
                <p className="text-slate-700 mb-3">
                  Time represents the duration of price movements. Different timeframes reveal different market perspectives. A stock can be in an uptrend on a daily chart but in a downtrend on a weekly chart.
                </p>
                <div className="bg-slate-50 rounded-lg p-4">
                  <p className="text-sm text-slate-600 mb-2"><strong>Common Timeframes:</strong></p>
                  <ul className="space-y-1 text-sm text-slate-600 ml-4">
                    <li>• <strong>Intraday:</strong> 1-min, 5-min, 15-min charts (scalping/day trading)</li>
                    <li>• <strong>Short-term:</strong> 30-min, 1-hour, 4-hour charts (intraday trading)</li>
                    <li>• <strong>Medium-term:</strong> Daily, Weekly charts (swing trading)</li>
                    <li>• <strong>Long-term:</strong> Monthly charts (position trading/investing)</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Types of Charts */}
        <div className="bg-white rounded-2xl p-8 shadow-lg mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-6">Types of Charts</h2>
          <div className="space-y-6">
            <p className="text-lg text-slate-700">
              Charts are visual representations of price data over time. Different chart types reveal different aspects of market behavior.
            </p>

            <div className="space-y-6">
              <div className="bg-blue-50 rounded-xl p-6 border-2 border-blue-200">
                <h3 className="text-xl font-semibold text-blue-900 mb-4">1. Line Chart</h3>
                <p className="text-slate-700 mb-4">
                  The simplest chart type. Connects closing prices with a continuous line. Useful for identifying overall trends but lacks detail about intraday price action.
                </p>
                <div className="bg-white rounded-lg p-4">
                  <p className="text-sm font-semibold text-slate-900 mb-2">Best For:</p>
                  <ul className="space-y-1 text-sm text-slate-600 ml-4">
                    <li>• Quick trend identification</li>
                    <li>• Long-term analysis</li>
                    <li>• Beginner traders</li>
                    <li>• Reducing chart noise</li>
                  </ul>
                </div>
                <div className="mt-4 bg-slate-100 p-4 rounded font-mono text-xs">
                  <pre className="text-slate-700">
{`Price Line Chart:
₹1100 |                    ●
      |                 ●
₹1050 |              ●
      |           ●
₹1000 |        ●
      |     ●
₹950  |  ●
      +─────────────────────
       Time →`}
                  </pre>
                </div>
              </div>

              <div className="bg-green-50 rounded-xl p-6 border-2 border-green-200">
                <h3 className="text-xl font-semibold text-green-900 mb-4">2. Bar Chart (OHLC Chart)</h3>
                <p className="text-slate-700 mb-4">
                  Shows four data points: Open, High, Low, Close. Each vertical line represents one time period with small horizontal ticks showing open (left) and close (right).
                </p>
                <div className="bg-white rounded-lg p-4">
                  <p className="text-sm font-semibold text-slate-900 mb-2">Best For:</p>
                  <ul className="space-y-1 text-sm text-slate-600 ml-4">
                    <li>• Understanding price range</li>
                    <li>• Identifying market volatility</li>
                    <li>• Professional traders</li>
                    <li>• Gap analysis</li>
                  </ul>
                </div>
                <div className="mt-4 bg-slate-100 p-4 rounded font-mono text-xs">
                  <pre className="text-slate-700">
{`Bar Chart Structure:
    High
     |
  ---|---  (Left tick = Open)
     |     (Right tick = Close)
    Low
    
Green bar = Close > Open (Bullish)
Red bar = Close < Open (Bearish)`}
                  </pre>
                </div>
              </div>

              <div className="bg-purple-50 rounded-xl p-6 border-2 border-purple-200">
                <h3 className="text-xl font-semibold text-purple-900 mb-4">3. Candlestick Chart</h3>
                <p className="text-slate-700 mb-4">
                  The most popular chart type among traders. Similar to bar charts but uses colored "bodies" to show the range between open and close, with "wicks" showing high and low. Originated in 18th century Japan for rice trading.
                </p>
                <div className="bg-white rounded-lg p-4">
                  <p className="text-sm font-semibold text-slate-900 mb-2">Best For:</p>
                  <ul className="space-y-1 text-sm text-slate-600 ml-4">
                    <li>• Pattern recognition</li>
                    <li>• Reading market sentiment quickly</li>
                    <li>• Intraday and swing trading</li>
                    <li>• Most versatile chart type</li>
                  </ul>
                </div>
                <div className="mt-4 bg-slate-100 p-4 rounded font-mono text-xs">
                  <pre className="text-slate-700">
{`Candlestick Structure:

Bullish (Green/White)   Bearish (Red/Black)
      High                    High
       |                       |
   ┌───┐                       |
   │   │ ← Body               ┌─┐
   │   │   (Open to Close)    │ │
   └───┘                      │ │
       |                      └─┘
      Low                      |
                              Low
                              
Large body = Strong momentum
Small body = Indecision
Long wicks = Rejection`}
                  </pre>
                </div>
              </div>
            </div>

            <div className="bg-gradient-to-r from-blue-50 to-purple-50 rounded-xl p-6 border-2 border-blue-200">
              <h3 className="text-lg font-semibold text-slate-900 mb-3">Chart Comparison Summary</h3>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead className="bg-slate-900 text-white">
                    <tr>
                      <th className="p-3 text-left">Chart Type</th>
                      <th className="p-3 text-left">Information</th>
                      <th className="p-3 text-left">Complexity</th>
                      <th className="p-3 text-left">Best Use</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white">
                    <tr className="border-b">
                      <td className="p-3 font-semibold">Line</td>
                      <td className="p-3">Close only</td>
                      <td className="p-3 text-green-600">Low</td>
                      <td className="p-3">Trend identification</td>
                    </tr>
                    <tr className="border-b bg-slate-50">
                      <td className="p-3 font-semibold">Bar</td>
                      <td className="p-3">OHLC</td>
                      <td className="p-3 text-yellow-600">Medium</td>
                      <td className="p-3">Volatility analysis</td>
                    </tr>
                    <tr>
                      <td className="p-3 font-semibold">Candlestick</td>
                      <td className="p-3">OHLC + Visual</td>
                      <td className="p-3 text-yellow-600">Medium</td>
                      <td className="p-3">Pattern trading</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

        {/* Dow Theory */}
        <div className="bg-white rounded-2xl p-8 shadow-lg mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-6">Dow Theory: The Foundation</h2>
          <div className="space-y-6">
            <p className="text-lg text-slate-700 leading-relaxed">
              Dow Theory, developed by Charles Dow in the late 1800s, is the grandfather of technical analysis. Though over a century old, its principles remain relevant today. Understanding Dow Theory is essential for grasping modern technical analysis.
            </p>

            <div className="bg-slate-100 rounded-xl p-6">
              <h3 className="text-xl font-semibold text-slate-900 mb-4">Six Principles of Dow Theory</h3>
              <div className="space-y-4">
                <div className="bg-white rounded-lg p-4">
                  <h4 className="font-semibold text-blue-700 mb-2">1. The Market Discounts Everything</h4>
                  <p className="text-sm text-slate-600">
                    All information—known and unknown, past and future expectations—is already reflected in market prices. This is why news often causes minimal price movement; it was already "priced in."
                  </p>
                </div>
                
                <div className="bg-white rounded-lg p-4">
                  <h4 className="font-semibold text-blue-700 mb-2">2. Three Types of Trends</h4>
                  <p className="text-sm text-slate-600 mb-3">
                    Markets move in three trend types, like ocean waves:
                  </p>
                  <ul className="text-sm text-slate-600 space-y-2 ml-4">
                    <li>• <strong>Primary Trend (1+ years):</strong> Major tide - overall market direction</li>
                    <li>• <strong>Secondary Trend (3 weeks-3 months):</strong> Waves - corrections within primary trend</li>
                    <li>• <strong>Minor Trend (&lt;3 weeks):</strong> Ripples - daily fluctuations (noise)</li>
                  </ul>
                </div>

                <div className="bg-white rounded-lg p-4">
                  <h4 className="font-semibold text-blue-700 mb-2">3. Primary Trends Have Three Phases</h4>
                  <p className="text-sm text-slate-600 mb-2">Bull markets:</p>
                  <ul className="text-sm text-slate-600 space-y-1 ml-4 mb-3">
                    <li>• <strong>Accumulation:</strong> Smart money buying while public is pessimistic</li>
                    <li>• <strong>Public Participation:</strong> Trend becomes obvious, public joins</li>
                    <li>• <strong>Distribution:</strong> Smart money selling to euphoric public</li>
                  </ul>
                  <p className="text-sm text-slate-600">Bear markets follow opposite phases.</p>
                </div>

                <div className="bg-white rounded-lg p-4">
                  <h4 className="font-semibold text-blue-700 mb-2">4. Indices Must Confirm</h4>
                  <p className="text-sm text-slate-600">
                    For a valid trend, multiple market indices should move in the same direction. If Nifty makes new highs but Bank Nifty doesn't, the trend is questionable.
                  </p>
                </div>

                <div className="bg-white rounded-lg p-4">
                  <h4 className="font-semibold text-blue-700 mb-2">5. Volume Confirms Trends</h4>
                  <p className="text-sm text-slate-600">
                    Volume should increase in the direction of the trend. In uptrends, volume should be higher on up days. In downtrends, volume should be higher on down days. Declining volume warns of possible reversal.
                  </p>
                </div>

                <div className="bg-white rounded-lg p-4">
                  <h4 className="font-semibold text-blue-700 mb-2">6. Trends Persist Until Clear Reversal</h4>
                  <p className="text-sm text-slate-600">
                    "The trend is your friend until it ends." Don't assume a reversal from minor corrections. Require clear evidence (lower lows in uptrend, higher highs in downtrend) before declaring trend change.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Practical Application */}
        <div className="bg-gradient-to-r from-blue-50 to-teal-50 rounded-2xl p-8 shadow-lg mb-8 border-2 border-blue-200">
          <h2 className="text-2xl font-bold text-slate-900 mb-6">Practical Application: Getting Started</h2>
          <div className="space-y-6">
            <div className="bg-white rounded-xl p-6">
              <h3 className="text-lg font-semibold text-slate-900 mb-4">What You Need to Begin</h3>
              <div className="grid md:grid-cols-2 gap-6">
                <div>
                  <h4 className="font-semibold text-blue-700 mb-3">Tools & Software</h4>
                  <ul className="space-y-2 text-sm text-slate-600">
                    <li>• Trading platform with charting (TradingView, Zerodha Kite, etc.)</li>
                    <li>• Real-time or end-of-day data</li>
                    <li>• Internet connection</li>
                    <li>• Paper trading account (practice)</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-semibold text-green-700 mb-3">Knowledge Prerequisites</h4>
                  <ul className="space-y-2 text-sm text-slate-600">
                    <li>• Basic understanding of stock markets</li>
                    <li>• How to read price quotes</li>
                    <li>• Buying and selling mechanics</li>
                    <li>• Patience and discipline</li>
                  </ul>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-xl p-6">
              <h3 className="text-lg font-semibold text-slate-900 mb-4">Your Learning Path</h3>
              <ol className="space-y-3">
                <li className="flex items-start gap-3">
                  <span className="bg-blue-600 text-white font-bold w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0">1</span>
                  <div>
                    <strong className="text-slate-900">Master chart reading:</strong>
                    <p className="text-sm text-slate-600">Spend 2 weeks just observing candlestick charts. Don't trade—just watch how patterns form and resolve.</p>
                  </div>
                </li>
                <li className="flex items-start gap-3">
                  <span className="bg-blue-600 text-white font-bold w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0">2</span>
                  <div>
                    <strong className="text-slate-900">Learn candlestick patterns:</strong>
                    <p className="text-sm text-slate-600">Study common patterns (next module). Practice identifying them on historical charts.</p>
                  </div>
                </li>
                <li className="flex items-start gap-3">
                  <span className="bg-blue-600 text-white font-bold w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0">3</span>
                  <div>
                    <strong className="text-slate-900">Understand support/resistance:</strong>
                    <p className="text-sm text-slate-600">These are the pillars of technical analysis. Mark them on charts daily.</p>
                  </div>
                </li>
                <li className="flex items-start gap-3">
                  <span className="bg-blue-600 text-white font-bold w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0">4</span>
                  <div>
                    <strong className="text-slate-900">Add indicators gradually:</strong>
                    <p className="text-sm text-slate-600">Start with moving averages, then add RSI, MACD. Don't overcomplicate.</p>
                  </div>
                </li>
                <li className="flex items-start gap-3">
                  <span className="bg-blue-600 text-white font-bold w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0">5</span>
                  <div>
                    <strong className="text-slate-900">Paper trade extensively:</strong>
                    <p className="text-sm text-slate-600">Minimum 3 months simulated trading before risking real money.</p>
                  </div>
                </li>
              </ol>
            </div>
          </div>
        </div>

        {/* Key Takeaways */}
        <div className="bg-gradient-to-r from-slate-900 to-slate-800 rounded-2xl p-8 shadow-lg mb-8 text-white">
          <h2 className="text-2xl font-bold mb-6">Key Takeaways</h2>
          <div className="space-y-4">
            <div className="flex items-start gap-3">
              <span className="text-2xl">1️⃣</span>
              <p className="text-lg">Technical analysis studies <strong>price, volume, and time</strong>—not company fundamentals.</p>
            </div>
            <div className="flex items-start gap-3">
              <span className="text-2xl">2️⃣</span>
              <p className="text-lg">Three chart types: <strong>Line (simplest), Bar (detailed), Candlestick (most popular)</strong>.</p>
            </div>
            <div className="flex items-start gap-3">
              <span className="text-2xl">3️⃣</span>
              <p className="text-lg">Dow Theory principles: <strong>Markets discount everything, trends persist, volume confirms</strong>.</p>
            </div>
            <div className="flex items-start gap-3">
              <span className="text-2xl">4️⃣</span>
              <p className="text-lg">Start simple—<strong>master chart reading before adding indicators</strong>.</p>
            </div>
            <div className="flex items-start gap-3">
              <span className="text-2xl">5️⃣</span>
              <p className="text-lg">Practice on historical data <strong>before risking real money</strong>.</p>
            </div>
          </div>
        </div>

        {/* Next Steps */}
        <div className="bg-white rounded-2xl p-8 shadow-lg text-center">
          <h2 className="text-2xl font-bold text-slate-900 mb-4">Ready for the Next Module?</h2>
          <p className="text-slate-600 mb-6">
            Now that you understand the basics, let's dive into candlestick patterns—the language of price action.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link to="/technical-analysis/candlestick-patterns-ta" className="px-8 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition">
              Next: Candlestick Patterns →
            </Link>
            <Link to="/technical-analysis" className="px-8 py-3 bg-slate-200 text-slate-700 font-semibold rounded-lg hover:bg-slate-300 transition">
              Back to Course Overview
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
